### ISSUE TITLE
How to build docker image?

### ISSUE THREAD

**Issue by 0xKoios** [dcajasn/Riskfolio-Lib#143]
This is my Dockerfile
```
FROM python:3.7.13
WORKDIR /app
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install numpy
RUN pip install pybind11
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD ["python3", "main.py"]
```
This is my requirements.txt
```
ccxt~=2.6.39
pandas~=1.3.5
riskfolio-lib~=4.0.3
```

I need help to build the image for use Riskfolio-Lib but I can't build and this is error logs
```
[+] Building 6.4s (10/12)                                                                                              
[+] Building 183.5s (11/12)                                                                                            
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 37B                                                                               0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 2B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.7.13                                                  2.2s
 => [internal] load build context                                                                                 0.4s
 => => transferring context: 1.19MB                                                                               0.3s
 => [1/8] FROM docker.io/library/python:3.7.13@sha256:8b743b1af852e554b98e2377f9c92221693225b85d984b23be6b033018  0.0s
 => CACHED [2/8] WORKDIR /app                                                                                     0.0s
 => CACHED [3/8] RUN /usr/local/bin/python -m pip install --upgrade pip                                           0.0s
 => CACHED [4/8] RUN pip install numpy                                                                            0.0s
 => CACHED [5/8] RUN pip install pybind11                                                                         0.0s
 => CACHED [6/8] COPY requirements.txt requirements.txt                                                           0.0s
 => ERROR [7/8] RUN pip install -r requirements.txt                                                             180.8s
------                                                                                                                 
 > [7/8] RUN pip install -r requirements.txt:                                                                          
#11 0.731 Collecting ccxt~=2.6.39                                                                                      
#11 0.852   Downloading ccxt-2.6.39-py2.py3-none-any.whl (3.4 MB)                                                      
#11 1.254      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 8.6 MB/s eta 0:00:00
#11 1.418 Collecting pandas~=1.3.5
#11 1.508   Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (10.7 MB)
#11 2.261      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 17.1 MB/s eta 0:00:00
#11 2.297 Collecting riskfolio-lib~=4.0.3
#11 2.309   Downloading Riskfolio-Lib-4.0.3.tar.gz (12.9 MB)
#11 3.071      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 19.8 MB/s eta 0:00:00
#11 3.639   Preparing metadata (setup.py): started
#11 3.886   Preparing metadata (setup.py): finished with status 'done'
#11 4.094 Collecting aiohttp>=3.8
#11 4.495   Downloading aiohttp-3.8.3-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (952 kB)
#11 4.538      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 952.9/952.9 kB 23.8 MB/s eta 0:00:00
#11 4.912 Collecting requests>=2.18.4
#11 4.951   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
#11 4.956      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 14.9 MB/s eta 0:00:00
#11 5.150 Collecting setuptools>=60.9.0
#11 5.314   Downloading setuptools-66.0.0-py3-none-any.whl (1.3 MB)
#11 5.381      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 19.5 MB/s eta 0:00:00
#11 5.403 Collecting aiodns>=1.1.1
#11 5.416   Downloading aiodns-3.0.0-py3-none-any.whl (5.0 kB)
#11 5.470 Collecting certifi>=2018.1.18
#11 5.482   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
#11 5.491      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 21.4 MB/s eta 0:00:00
#11 5.665 Collecting cryptography>=2.6.1
#11 5.700   Downloading cryptography-39.0.0-cp36-abi3-manylinux_2_28_aarch64.whl (4.0 MB)
#11 5.928      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 17.5 MB/s eta 0:00:00
#11 6.060 Collecting yarl>=1.7.2
#11 6.092   Downloading yarl-1.8.2-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (227 kB)
#11 6.101      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.7/227.7 kB 27.4 MB/s eta 0:00:00
#11 6.127 Collecting python-dateutil>=2.7.3
#11 6.139   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
#11 6.151      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 23.5 MB/s eta 0:00:00
#11 6.199 Collecting pytz>=2017.3
#11 6.355   Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
#11 6.381      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 kB 20.5 MB/s eta 0:00:00
#11 6.388 Requirement already satisfied: numpy>=1.19.2 in /usr/local/lib/python3.7/site-packages (from pandas~=1.3.5->-r requirements.txt (line 2)) (1.21.6)
#11 6.496 Collecting scipy>=1.0.1
#11 6.511   Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (36.1 MB)
#11 8.785      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.1/36.1 MB 14.7 MB/s eta 0:00:00
#11 8.931 Collecting matplotlib>=3.3.0
#11 9.002   Downloading matplotlib-3.5.3-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.6 MB)
#11 9.817      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 13.2 MB/s eta 0:00:00
#11 9.951 Collecting cvxpy>=1.0.25
#11 10.03   Downloading cvxpy-1.3.0.tar.gz (1.3 MB)
#11 10.10      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 19.5 MB/s eta 0:00:00
#11 10.28   Installing build dependencies: started
#11 77.86   Installing build dependencies: still running...
#11 161.1   Installing build dependencies: still running...
#11 164.3   Installing build dependencies: finished with status 'done'
#11 164.3   Getting requirements to build wheel: started
#11 164.5   Getting requirements to build wheel: finished with status 'done'
#11 164.5   Preparing metadata (pyproject.toml): started
#11 164.7   Preparing metadata (pyproject.toml): finished with status 'done'
#11 164.8 Collecting scikit-learn>=0.22.0
#11 164.9   Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (24.6 MB)
#11 169.8      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 4.3 MB/s eta 0:00:00
#11 170.1 Collecting statsmodels>=0.10.1
#11 170.1   Downloading statsmodels-0.13.5-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (9.6 MB)
#11 170.7      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 16.2 MB/s eta 0:00:00
#11 170.8 Collecting arch>=4.15
#11 171.3   Downloading arch-5.3.1-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (883 kB)
#11 171.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.2/883.2 kB 25.0 MB/s eta 0:00:00
#11 171.3 Collecting xlsxwriter>=1.3.7
#11 171.7   Downloading XlsxWriter-3.0.7-py3-none-any.whl (152 kB)
#11 171.7      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 kB 11.8 MB/s eta 0:00:00
#11 171.7 Collecting networkx>=2.5.1
#11 171.7   Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
#11 171.8      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 19.4 MB/s eta 0:00:00
#11 172.0 Collecting astropy>=4.3.1
#11 172.7   Downloading astropy-4.3.1.tar.gz (7.6 MB)
#11 173.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 12.7 MB/s eta 0:00:00
#11 173.9   Installing build dependencies: started
#11 179.7   Installing build dependencies: finished with status 'done'
#11 179.7   Getting requirements to build wheel: started
#11 180.0   Getting requirements to build wheel: finished with status 'error'
#11 180.0   error: subprocess-exited-with-error
#11 180.0   
#11 180.0   × Getting requirements to build wheel did not run successfully.
#11 180.0   │ exit code: 1
#11 180.0   ╰─> [27 lines of output]
#11 180.0       Traceback (most recent call last):
#11 180.0         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
#11 180.0           main()
#11 180.0         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
#11 180.0           json_out['return_val'] = hook(**hook_input['kwargs'])
#11 180.0         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#11 180.0           return hook(config_settings)
#11 180.0         File "/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
#11 180.0           return self._get_build_requires(config_settings, requirements=['wheel'])
#11 180.0         File "/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
#11 180.0           self.run_setup()
#11 180.0         File "/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
#11 180.0           exec(code, locals())
#11 180.0         File "<string>", line 70, in <module>
#11 180.0         File "/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/extension_helpers/_setup_helpers.py", line 67, in get_extensions
#11 180.0           ext_modules.extend(setuppkg.get_extensions())
#11 180.0         File "./astropy/modeling/setup_package.py", line 59, in get_extensions
#11 180.0           from jinja2 import Environment, FileSystemLoader
#11 180.0         File "/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/jinja2/__init__.py", line 33, in <module>
#11 180.0           from jinja2.environment import Environment, Template
#11 180.0         File "/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/jinja2/environment.py", line 15, in <module>
#11 180.0           from jinja2 import nodes
#11 180.0         File "/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/jinja2/nodes.py", line 19, in <module>
#11 180.0           from jinja2.utils import Markup
#11 180.0         File "/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/jinja2/utils.py", line 642, in <module>
#11 180.0           from markupsafe import Markup, escape, soft_unicode
#11 180.0       ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/tmp/pip-build-env-vkndhwen/overlay/lib/python3.7/site-packages/markupsafe/__init__.py)
#11 180.0       [end of output]
#11 180.0   
#11 180.0   note: This error originates from a subprocess, and is likely not a problem with pip.
#11 180.0 error: subprocess-exited-with-error
#11 180.0 
#11 180.0 × Getting requirements to build wheel did not run successfully.
#11 180.0 │ exit code: 1
#11 180.0 ╰─> See above for output.
#11 180.0 
#11 180.0 note: This error originates from a subprocess, and is likely not a problem with pip.
------
executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1
```

**Comment by dcajasn** [comment]
Hi @0xKoios,

This is not a Riskfolio-Lib issue. On the other hand, I've never worked with docker, so I don't know how to do it.

Best,
Dany
