### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by Jacques2101** [dcajasn/Riskfolio-Lib#193]
Hi i am trying to install Eiskfolio-lib using `pip install riskfolio-lib`but get an error message which is : 

what can I do to install riskfolio-lib ? 

```
Collecting osqp>=0.6.2 (from cvxpy>=1.4.0->riskfolio-lib)
  Using cached osqp-0.6.5.tar.gz (228 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [118 lines of output]
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2023.12.21-py3-none-any.whl.metadata (9.8 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-69.2.0-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB)
      Collecting qdldl
        Using cached qdldl-0.1.7.post0.tar.gz (70 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting numpy==1.21.6 (from oldest-supported-numpy)
        Using cached numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl.metadata (2.1 kB)
      Collecting packaging>=20 (from setuptools_scm>=6.2)
        Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
      Collecting typing-extensions (from setuptools_scm>=6.2)
        Using cached typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
      Collecting tomli>=1 (from setuptools_scm>=6.2)
        Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
      Collecting scipy>=0.13.2 (from qdldl)
        Using cached scipy-1.12.0-cp310-cp310-macosx_12_0_arm64.whl.metadata (112 kB)
      INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
        Using cached scipy-1.11.4-cp310-cp310-macosx_12_0_arm64.whl.metadata (112 kB)
      Using cached oldest_supported_numpy-2023.12.21-py3-none-any.whl (4.9 kB)
      Using cached numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
      Using cached setuptools-69.2.0-py3-none-any.whl (821 kB)
      Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
      Using cached setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
      Using cached packaging-24.0-py3-none-any.whl (53 kB)
      Using cached scipy-1.11.4-cp310-cp310-macosx_12_0_arm64.whl (29.8 MB)
      Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Using cached typing_extensions-4.10.0-py3-none-any.whl (33 kB)
      Building wheels for collected packages: qdldl
        Building wheel for qdldl (pyproject.toml): started
        Building wheel for qdldl (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for qdldl (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [65 lines of output]
            running bdist_wheel
            running build
            running build_ext
            Traceback (most recent call last):
              File "<string>", line 81, in build_extensions
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/subprocess.py", line 421, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/subprocess.py", line 503, in run
                with Popen(*popenargs, **kwargs) as process:
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/subprocess.py", line 971, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/subprocess.py", line 1863, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 410, in build_wheel
                return self._build_with_temp_dir(
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
                self.run_setup()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
                exec(code, locals())
              File "<string>", line 113, in <module>
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
                return distutils.core.setup(**attrs)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
                self.run_command("build")
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
                self.run_command(cmd_name)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
                _build_ext.run(self)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-iq_w1ehd/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
                self.build_extensions()
              File "<string>", line 83, in build_extensions
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
      Failed to build qdldl
      ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by dcajasn** [comment]
Hi @Jacques2101,

It's a problem with cvxpy, try pip install -U cvxpy before installing Riskfolio-Lib.

Best,
Dany

**Comment by Jacques2101** [comment]
i have also an error message with pip install -U cvxpy

```
Collecting cvxpy
  Using cached cvxpy-1.4.2-cp310-cp310-macosx_10_9_universal2.whl.metadata (8.8 kB)
Collecting osqp>=0.6.2 (from cvxpy)
  Using cached osqp-0.6.5.tar.gz (228 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [118 lines of output]
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2023.12.21-py3-none-any.whl.metadata (9.8 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-69.2.0-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB)
      Collecting qdldl
        Using cached qdldl-0.1.7.post0.tar.gz (70 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting numpy==1.21.6 (from oldest-supported-numpy)
        Using cached numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl.metadata (2.1 kB)
      Collecting packaging>=20 (from setuptools_scm>=6.2)
        Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
      Collecting typing-extensions (from setuptools_scm>=6.2)
        Using cached typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
      Collecting tomli>=1 (from setuptools_scm>=6.2)
        Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
      Collecting scipy>=0.13.2 (from qdldl)
        Using cached scipy-1.12.0-cp310-cp310-macosx_12_0_arm64.whl.metadata (112 kB)
      INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
        Using cached scipy-1.11.4-cp310-cp310-macosx_12_0_arm64.whl.metadata (112 kB)
      Using cached oldest_supported_numpy-2023.12.21-py3-none-any.whl (4.9 kB)
      Using cached numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
      Using cached setuptools-69.2.0-py3-none-any.whl (821 kB)
      Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
      Using cached setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
      Using cached packaging-24.0-py3-none-any.whl (53 kB)
      Using cached scipy-1.11.4-cp310-cp310-macosx_12_0_arm64.whl (29.8 MB)
      Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Using cached typing_extensions-4.10.0-py3-none-any.whl (33 kB)
      Building wheels for collected packages: qdldl
        Building wheel for qdldl (pyproject.toml): started
        Building wheel for qdldl (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for qdldl (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [65 lines of output]
            running bdist_wheel
            running build
            running build_ext
            Traceback (most recent call last):
              File "<string>", line 81, in build_extensions
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/subprocess.py", line 421, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/subprocess.py", line 503, in run
                with Popen(*popenargs, **kwargs) as process:
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/subprocess.py", line 971, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/subprocess.py", line 1863, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/Users/jacques/miniconda3/envs/data/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 410, in build_wheel
                return self._build_with_temp_dir(
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
                self.run_setup()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
                exec(code, locals())
              File "<string>", line 113, in <module>
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
                return distutils.core.setup(**attrs)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
                self.run_command("build")
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
                self.run_command(cmd_name)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
                super().run_command(command)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
                _build_ext.run(self)
              File "/private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-build-env-q1bcwt0d/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
                self.build_extensions()
              File "<string>", line 83, in build_extensions
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
      Failed to build qdldl
      ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
