### ISSUE TITLE
UnboundLocalError: local variable 'risk' referenced before assignment

### ISSUE THREAD

**Issue by cryptocoinserver** [dcajasn/Riskfolio-Lib#62]
```
Traceback (most recent call last):
  File "/tmp/ipykernel_1100960/1703788391.py", line 84, in objective
    train_portfolio = vbt.Portfolio.from_order_func(
  File "/home/jupyter/Jupyter/notebook/lib/python3.8/site-packages/vectorbt/portfolio/base.py", line 3918, in from_order_func
    order_records, log_records = simulate_func(
  File "/home/jupyter/Jupyter/notebook/lib/python3.8/site-packages/vectorbt/portfolio/nb.py", line 2918, in simulate_nb
    pre_segment_out = pre_segment_func_nb(pre_seg_ctx, *pre_group_out, *pre_segment_args)
  File "/tmp/ipykernel_1100960/2778963701.py", line 28, in pre_segment_func_nb
    best_sharpe_ratio, weights = find_weights_nb(c, close, opt)
  File "/tmp/ipykernel_1100960/2757597337.py", line 21, in riskfolio_find_weights
    w = port.optimization(model='Classic', obj=opt['obj'], rm=opt['rm'], kelly=kelly, rf=rf, hist=opt['hist'])
  File "/home/jupyter/Jupyter/notebook/lib/python3.8/site-packages/riskfolio/Portfolio.py", line 1529, in optimization
    constraints += [risk <= 1]
UnboundLocalError: local variable 'risk' referenced before assignment
```

Did I miss something? I run an optimization on the parameters. This shows up often.

Thank you for your help.

**Comment by dcajasn** [comment]
You are using a risk measure that is not available for riskfolio-lib.
